---
- name: Import node apt-key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add node repository
  apt_repository: repo='deb https://deb.nodesource.com/node_4.x trusty main'

- name: Update package list
  apt: update_cache=yes

- name: Install NodeJS package
  apt: name=nodejs state=present

- name: Install npm packages
  npm: name={{ item }} global=yes
  with_items:
    - gulp
    - bower
