---
- name: Ensure postgresql packages are installed
  apt: name={{ item }}
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: Create postgresql user
  become_user: postgres
  postgresql_user: name=vagrant password=vagrant role_attr_flags=SUPERUSER

- name: Create postgresql database
  become_user: postgres
  postgresql_db: name=vagrant
